---
# ansible-playbook -i inventory/local/hosts.ini --flush-cache -b -u vagrant mmo.yml -t prometheus
- hosts: k8s-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: false
  vars:
    # Need to disable pipelining for bootstrap-os as some systems have requiretty in sudoers set, which makes pipelining
    # fail. bootstrap-os fixes this on these systems, so in later plays it can be enabled.
    ansible_ssh_pipelining: false
  roles:
    - { role: kubespray-defaults}
    - { role: mmo/traefik, tags: traefik}
    - { role: mmo/prometheus, tags: prometheus}